<a href="https://colab.research.google.com/github/Weeqa/dap-2024/blob/main/les04/4lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Лабораторная работа №4. Анализ данных пассажиров "Титаника"**

Используя набор данных titanic.csv выполните следующие 10 заданий.
1. Создайте DataFarame из файла titanic.csv, в качестве индекса используйте столбец "PassengerId"

In [4]:
import numpy as np
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving titanic.csv to titanic.csv

In [5]:
import numpy as np
import pandas as pd
titanik_df = pd.read_csv("titanic.csv", index_col='PassengerId')
titanik_df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

2. Просмотрите первые 6 строк

In [7]:
import numpy as np
import pandas as pd
titanik_df.head(6)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

3. Выведите описание данных

In [8]:
import numpy as np
import pandas as pd
titanik_df.describe() # Описание данных

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

4. Сколько мужчин / женщин находилось на борту?

In [11]:
male = titanik_df ["Sex"] == 'male'
female = titanik_df ["Sex"] == 'female'
print("Женщин на борту: ", female.sum(), ", мужчин на борту - ", male.sum())

Женщин на борту:  314 , мужчин на борту -  577

5. Выведите распределение переменной Pclass (социально-экономический статус) и это же распределение, только для мужчин / женщин по отдельности. Сколько было мужчин 2-го класса

In [26]:
male = titanik_df['Sex'] == 'male'
female = titanik_df['Sex'] == 'female'

pclass = titanik_df['Pclass']
print("Распредление для всех пассажиров:\n", pclass.value_counts())
print("Распределение для мужчин:\n", pclass[male].value_counts())
print("Распределение для женщин:\n", pclass[female].value_counts())

print("Количество мужчин во втором классе: ", pclass[male].value_counts().loc[2])

Распредление для всех пассажиров Pclass
3    491
1    216
2    184
Name: count, dtype: int64
Распределение для мужчин:
 Pclass
3    347
1    122
2    108
Name: count, dtype: int64
Распределение для женщин:
 Pclass
3    144
1     94
2     76
Name: count, dtype: int64
Количество мужчин во втором классе:  108

6. Каковы медиана и среднеквадрати́чное отклонение платежей (Fare)? Округлите до 2 десятичных знаков.

In [17]:
median = round(titanik_df['Fare'].median(), 3)
std = round(titanik_df['Fare'].std(), 3)
print("Медиана ", median)
print("Среднеквадратичное отклонение ", std)

Медиана  14.454
Среднеквадратичное отклонение  49.693

7. Правда ли, что люди моложе 30 лет выживали чаще, чем люди старше 60 лет? Каковы доли выживших в обеих группах?

In [14]:
titanik_df_30 = titanik_df[titanik_df['Age'] < 30]
titanik_df_60 = titanik_df[titanik_df['Age'] > 60]
survived30 = round(titanik_df_30['Survived'].mean(), 3)
survived60 = round(titanik_df_60['Survived'].mean(), 3)
print("Процент выживших моложе 30 лет: ", survived30, ", процент выживших старше 60 лет: ", survived60)
print('Правда') if survived30 > survived60 else print('False')

Процент выживших моложе 30 лет:  0.406 , процент выживших старше 60 лет:  0.227
Правда

8. Правда ли, что женщины выживали чаще мужчин? Каковы доли выживших в обеих группах?

In [15]:
women = titanik_df[titanik_df['Sex'] == "female"]
men = titanik_df[titanik_df['Sex'] == "male"]
survived_women = round(women['Survived'].mean(), 3)
survived_men = round(men['Survived'].mean(), 3)
print("Процент выживших женщин: ", survived_women, ", процент выживших мужчин: ", survived_men)
print('Правда') if survived_women > survived_men else print('False')

Процент выживших женщин:  0.742 , процент выживших мужчин:  0.189
Правда

9. Найдите самое популярное имя среди пассажиров Титаника мужского пола?

In [31]:
male = titanik_df['Sex'] == 'male'
male_names = titanik_df.loc[male, 'Name'].str.split(" ").str[2]
most_mode_name = male_names.mode().iloc[0]
print(f"{most_mode_name} самое распространненое мужское имя")

William самое распространненое мужское имя

10. Как отличается средний возраст мужчин / женщин в зависимости от класса обслуживания? Выберите верные утверждения:

В среднем мужчины 1-го класса старше 40 лет В среднем женщины 1-го класса старше 40 лет -

Мужчины всех классов в среднем старше женщин того же класса +

В среднем люди в 1 классе старше, чем во 2-ом, а те старше представителей 3-го класса +

In [18]:
titanik_df.pivot_table('Age', index='Sex', columns='Pclass', aggfunc='mean')

Pclass          1          2          3
Sex
female  34.611765  28.722973  21.750000
male    41.281386  30.740707  26.507589

11. Сравните возраст у спасенных и у погибших пасажиров. Средний возраст погибших выше, верно?

In [16]:
titanik_survived = titanik_df[titanik_df['Survived'] == 1]
titanik_not_survived = titanik_df[titanik_df['Survived'] == 0]
titanik_survived_percent = round(titanik_survived['Age'].mean(), 3)
titanik_not_survived_percent = round(titanik_not_survived['Age'].mean(), 3)
print("Средний возраст выживших: ", titanik_survived_percent, ", средний возраст погибших: ", titanik_not_survived_percent)
print('Правда') if titanik_not_survived_percent > titanik_survived_percent else print('False')

titanik_df.pivot_table('Age', columns='Survived', aggfunc='mean')

Средний возраст выживших:  28.344 , средний возраст погибших:  30.626
Правда

Survived          0         1
Age       30.626179  28.34369